github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAT }}

# codeowners:
# - path:  "*"
#   owner: "@paketo-buildpacks/utilities-maintainers"

helpers:
  "bin/helper": "$GOMOD/cmd/helper"

package:
  repositories:   ["docker.io/initializbuildpacks/ca-certificates"]
  register:       true
  registry_token: ${{ secrets.PAT }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.INITIALIZ_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.INITIALIZ_BUILDPACKS_DOCKERHUB_PASSWORD }}