github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAT }}

codeowners:
- path:  "*"
  owner: "@initializ-buildpacks/utilities-maintainers"

package:
  repositories:   ["docker.io/initializbuildpacks/ca-certificates"]
  register:       true
  registry_token: ${{ secrets.PAT }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.INITIALIZ_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.INITIALIZ_BUILDPACKS_DOCKERHUB_PASSWORD }}
